import { Membro, EventoAgenda, ParticipanteConfra, Transacao, ItemFrequencia } from '../types';

export interface MensalidadeHistoricoItem {
  arrecadado: number;
  ofertaOutros: number;
  debitos: number;
  valorRestante: number;
  faltou: number;
  sobraAnterior: number;
  valorConta: number;
  percentual: number;
  despesasDetalhadas: { descricao: string; valor: number }[];
}

// 29 Membros Oficiais extraídos da planilha
export const OFICIAL_MEMBROS: Membro[] = [
  { id: 'm1', nome: 'Andressa Pyrro', funcao: 'Líder de Adoração', ativo: true },
  { id: 'm2', nome: 'Angélica', funcao: 'Vocalista', ativo: true },
  { id: 'm3', nome: 'Aurenir', funcao: 'Vocalista', ativo: true },
  { id: 'm4', nome: 'Edigar Brito', funcao: 'Mesa de Som', ativo: true },
  { id: 'm5', nome: 'Eduarda Medeiros', funcao: 'Violonista | Baixista', ativo: true },
  { id: 'm6', nome: 'Eduardo Angelo', funcao: 'Guitarrista | Violão', ativo: true },
  { id: 'm7', nome: 'Eduardo Medeiros', funcao: 'Vocalista | Multinstrumentos', ativo: true },
  { id: 'm8', nome: 'Gabriel Pereira', funcao: 'Baterista', ativo: true },
  { id: 'm9', nome: 'Gilson Nobrega', funcao: 'Violonista | Vocalista', ativo: true },
  { id: 'm10', nome: 'Helenice Batista', funcao: 'Violonista | Baixista', ativo: true },
  { id: 'm11', nome: 'Hellen Silva', funcao: 'Sonoplasta', ativo: true },
  { id: 'm12', nome: 'Hercílio', funcao: 'Vocalista', ativo: true },
  { id: 'm13', nome: 'Ismael Junior', funcao: 'Baixista', ativo: true },
  { id: 'm14', nome: 'Jamilly Nobrega', funcao: 'Líder de Adoração', ativo: true },
  { id: 'm15', nome: 'Jerdely', funcao: 'Tecladista | Vocalista', ativo: true },
  { id: 'm16', nome: 'João Victor', funcao: 'Baterista', ativo: true },
  { id: 'm17', nome: 'John Araújo', funcao: 'Baterista', ativo: true },
  { id: 'm18', nome: 'Laís', funcao: 'Líder de Adoração', ativo: true },
  { id: 'm19', nome: 'Lucas Gabriel', funcao: 'Baterista', ativo: true },
  { id: 'm20', nome: 'Lucas Lopes', funcao: 'Baterista', ativo: true },
  { id: 'm21', nome: 'Lucas Sales', funcao: 'Baterista', ativo: true },
  { id: 'm22', nome: 'Luiz Emmanuel', funcao: 'Guitarrista | Violão', ativo: true },
  { id: 'm23', nome: 'Maria Eduarda', funcao: 'Violonista | Vocalista', ativo: true },
  { id: 'm24', nome: 'Naara Oliveira', funcao: 'Vocalista', ativo: true },
  { id: 'm25', nome: 'Narjan Andrade', funcao: 'Tecladista | Vocalista', ativo: true },
  { id: 'm26', nome: 'Rafael Pyrro', funcao: 'Baixista', ativo: true },
  { id: 'm27', nome: 'Talita Costa', funcao: 'Tecladista', ativo: true },
  { id: 'm28', nome: 'Thiago de Souza', funcao: 'Vocalista', ativo: true },
  { id: 'm29', nome: 'Vitor Nascimento', funcao: 'Guitarrista', ativo: true },
];

// Dados Consolidados Mês a Mês da Planilha (Janeiro a Dezembro 2026)
export const OFICIAL_HISTORICO_MESES: Record<number, MensalidadeHistoricoItem> = {
  1: {
    arrecadado: 260.00,
    ofertaOutros: 147.50,
    debitos: 280.66,
    valorRestante: 126.84,
    faltou: 40.00,
    sobraAnterior: 186.75,
    valorConta: 313.59,
    percentual: 87,
    despesasDetalhadas: [
      { descricao: 'Louve App', valor: 24.99 },
      { descricao: 'Moisés VS', valor: 9.99 },
      { descricao: 'Salgados + Refri Reunião Geral', valor: 60.00 },
      { descricao: 'Compra M-Vave (Sistema Sem Fio Fone)', valor: 185.68 },
    ],
  },
  2: {
    arrecadado: 170.00,
    ofertaOutros: 48.09,
    debitos: 44.98,
    valorRestante: 173.11,
    faltou: 130.00,
    sobraAnterior: 313.59,
    valorConta: 486.70,
    percentual: 67,
    despesasDetalhadas: [
      { descricao: 'Louve App', valor: 34.99 },
      { descricao: 'Moisés VS', valor: 9.99 },
    ],
  },
  3: {
    arrecadado: 170.00,
    ofertaOutros: 33.35,
    debitos: 574.96,
    valorRestante: -371.61,
    faltou: 110.00,
    sobraAnterior: 486.70,
    valorConta: 115.09,
    percentual: 68,
    despesasDetalhadas: [
      { descricao: 'Louve App', valor: 34.99 },
      { descricao: 'Moisés VS', valor: 9.99 },
      { descricao: 'Oferta Everton Bruno', valor: 120.00 },
      { descricao: 'Caixas de Pastilhas', valor: 409.98 },
    ],
  },
  4: {
    arrecadado: 150.00,
    ofertaOutros: 443.94,
    debitos: 295.99,
    valorRestante: 297.95,
    faltou: 100.00,
    sobraAnterior: 115.09,
    valorConta: 413.04,
    percentual: 76,
    despesasDetalhadas: [
      { descricao: 'Louve App', valor: 34.99 },
      { descricao: 'Bateria Violão', valor: 22.00 },
      { descricao: '1ª Parcela Microfones', valor: 239.00 },
    ],
  },
  5: {
    arrecadado: 130.00,
    ofertaOutros: 113.76,
    debitos: 545.81,
    valorRestante: -302.05,
    faltou: 110.00,
    sobraAnterior: 413.04,
    valorConta: 110.99,
    percentual: 67,
    despesasDetalhadas: [
      { descricao: 'Louve App', valor: 34.99 },
      { descricao: 'Pele Bateria', valor: 120.00 },
      { descricao: 'Encordoamento Violão', valor: 57.00 },
      { descricao: 'Pilhas e Bateria', valor: 129.81 },
      { descricao: '2ª Parcela Microfones', valor: 239.00 },
    ],
  },
  6: {
    arrecadado: 100.00,
    ofertaOutros: 83.59,
    debitos: 273.99,
    valorRestante: -90.40,
    faltou: 200.00,
    sobraAnterior: 110.99,
    valorConta: 20.59,
    percentual: 57,
    despesasDetalhadas: [
      { descricao: 'Louve App', valor: 34.99 },
      { descricao: '3ª Parcela Microfones', valor: 239.00 },
    ],
  },
  7: {
    arrecadado: 190.00,
    ofertaOutros: 211.34,
    debitos: 273.99,
    valorRestante: 127.35,
    faltou: 100.00,
    sobraAnterior: 20.59,
    valorConta: 147.94,
    percentual: 76,
    despesasDetalhadas: [
      { descricao: 'Louve App', valor: 34.99 },
      { descricao: '4ª Parcela Microfones', valor: 239.00 },
    ],
  },
  8: {
    arrecadado: 120.00,
    ofertaOutros: 1.87,
    debitos: 54.89,
    valorRestante: 66.98,
    faltou: 170.00,
    sobraAnterior: 147.94,
    valorConta: 214.92,
    percentual: 55,
    despesasDetalhadas: [
      { descricao: 'Louve App', valor: 34.99 },
      { descricao: 'Adaptador USB', valor: 19.90 },
    ],
  },
  9: {
    arrecadado: 160.00,
    ofertaOutros: 0.25,
    debitos: 216.84,
    valorRestante: -56.59,
    faltou: 120.00,
    sobraAnterior: 214.92,
    valorConta: 158.33,
    percentual: 68,
    despesasDetalhadas: [
      { descricao: 'Louve App', valor: 34.99 },
      { descricao: 'Encordoamento Guitarra', valor: 35.00 },
      { descricao: 'Amendoim Para Venda', valor: 78.10 },
      { descricao: 'Moisés App', valor: 10.00 },
      { descricao: 'Prato Bateria', valor: 136.85 },
    ],
  },
  10: {
    arrecadado: 0.00,
    ofertaOutros: 0.00,
    debitos: 0.00,
    valorRestante: 0.00,
    faltou: 90.00,
    sobraAnterior: 158.33,
    valorConta: 158.33,
    percentual: 11,
    despesasDetalhadas: [
      { descricao: 'Louve App', valor: 34.99 },
    ],
  },
  11: {
    arrecadado: 0.00,
    ofertaOutros: 0.00,
    debitos: 0.00,
    valorRestante: 0.00,
    faltou: 0.00,
    sobraAnterior: 158.33,
    valorConta: 158.33,
    percentual: 11,
    despesasDetalhadas: [
      { descricao: 'Louve App', valor: 34.99 },
    ],
  },
  12: {
    arrecadado: 0.00,
    ofertaOutros: 0.00,
    debitos: 0.00,
    valorRestante: 0.00,
    faltou: 0.00,
    sobraAnterior: 158.33,
    valorConta: 158.33,
    percentual: 11,
    despesasDetalhadas: [
      { descricao: 'Louve App', valor: 34.99 },
    ],
  },
};

// Pagamento de Mensalidades por Membro em cada mês (1 a 12)
// True = Pago (ou nome constando na planilha), False = Não pago
export const OFICIAL_PAGAMENTOS_MATRIZ: Record<string, number[]> = {
  'Andressa Pyrro': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  'Angélica': [1, 2, 3, 4, 5, 6, 7, 8],
  'Aurenir': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  'Edigar Brito': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  'Eduarda Medeiros': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  'Eduardo Angelo': [6, 7, 8, 9, 10, 11, 12],
  'Eduardo Medeiros': [1, 2, 3, 4, 5, 8, 9, 10, 11, 12],
  'Gabriel Pereira': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  'Gilson Nobrega': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  'Helenice Batista': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  'Hellen Silva': [1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12],
  'Hercílio': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  'Ismael Junior': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  'Jamilly Nobrega': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  'Jerdely': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  'João Victor': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  'John Araújo': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  'Laís': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  'Lucas Gabriel': [6, 7, 8, 9, 10, 11, 12],
  'Lucas Lopes': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  'Lucas Sales': [8, 9, 10, 11, 12],
  'Luiz Emmanuel': [6, 7, 8, 9, 10, 11, 12],
  'Maria Eduarda': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  'Naara Oliveira': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  'Narjan Andrade': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  'Rafael Pyrro': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  'Talita Costa': [8, 9, 10, 11, 12],
  'Thiago de Souza': [6, 7, 8, 9, 10, 11, 12],
  'Vitor Nascimento': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
};

// Eventos e Agenda extraídos da Página 3 do PDF
export const OFICIAL_EVENTOS: EventoAgenda[] = [
  {
    id: 'ev_1',
    titulo: 'Reunião Geral',
    data: '2026-01-06',
    dataFormatada: '06/01/2026',
    mes: 1,
    dia: 6,
    categoria: 'Reunião Geral',
    gcal: '20260106/20260107',
  },
  {
    id: 'ev_2',
    titulo: 'Reunião Geral',
    data: '2026-02-03',
    dataFormatada: '03/02/2026',
    mes: 2,
    dia: 3,
    categoria: 'Reunião Geral',
    gcal: '20260203/20260204',
  },
  {
    id: 'ev_3',
    titulo: 'Reunião Geral',
    data: '2026-03-03',
    dataFormatada: '03/03/2026',
    mes: 3,
    dia: 3,
    categoria: 'Reunião Geral',
    gcal: '20260303/20260304',
  },
  {
    id: 'ev_4',
    titulo: 'Reunião Geral',
    data: '2026-04-07',
    dataFormatada: '07/04/2026',
    mes: 4,
    dia: 7,
    categoria: 'Reunião Geral',
    gcal: '20260407/20260408',
  },
  {
    id: 'ev_5',
    titulo: 'Reunião Geral',
    data: '2026-05-05',
    dataFormatada: '05/05/2026',
    mes: 5,
    dia: 5,
    categoria: 'Reunião Geral',
    gcal: '20260505/20260506',
  },
  {
    id: 'ev_6',
    titulo: 'Reunião Geral',
    data: '2026-06-02',
    dataFormatada: '02/06/2026',
    mes: 6,
    dia: 2,
    categoria: 'Reunião Geral',
    gcal: '20260602/20260603',
  },
  {
    id: 'ev_7',
    titulo: 'Reunião Geral',
    data: '2026-07-07',
    dataFormatada: '07/07/2026',
    mes: 7,
    dia: 7,
    categoria: 'Reunião Geral',
    gcal: '20260707/20260708',
  },
  {
    id: 'ev_8',
    titulo: 'Reunião Geral',
    data: '2026-08-04',
    dataFormatada: '04/08/2026',
    mes: 8,
    dia: 4,
    categoria: 'Reunião Geral',
    gcal: '20260804/20260805',
  },
  {
    id: 'ev_9',
    titulo: 'Reunião Geral',
    data: '2026-09-01',
    dataFormatada: '01/09/2026',
    mes: 9,
    dia: 1,
    categoria: 'Reunião Geral',
    gcal: '20260901/20260902',
  },
  {
    id: 'ev_10',
    titulo: 'Ensaio para Louvorzão',
    data: '2026-09-08',
    dataFormatada: '08/09/2026',
    mes: 9,
    dia: 8,
    categoria: 'Ensaio',
    escalados: 'Andressa Pyrro, Gilson Nobrega, John Araújo, Laís, Maria Eduarda, Narjan Andrade, Rafael Pyrro, Vitor Nascimento',
    gcal: '20260908/20260909',
  },
  {
    id: 'ev_11',
    titulo: 'Louvorzão Sião',
    data: '2026-09-12',
    dataFormatada: '12/09/2026',
    mes: 9,
    dia: 12,
    categoria: 'Culto',
    gcal: '20260912/20260913',
  },
  {
    id: 'ev_12',
    titulo: 'Conferência Freedom - Dia 1',
    data: '2026-10-01',
    dataFormatada: '01/10/2026',
    mes: 10,
    dia: 1,
    categoria: 'Culto',
    gcal: '20261001/20261002',
  },
  {
    id: 'ev_13',
    titulo: 'Conferência Freedom - Dia 2',
    data: '2026-10-02',
    dataFormatada: '02/10/2026',
    mes: 10,
    dia: 2,
    categoria: 'Culto',
    gcal: '20261002/20261003',
  },
  {
    id: 'ev_14',
    titulo: 'Conferência Freedom - Dia 3',
    data: '2026-10-03',
    dataFormatada: '03/10/2026',
    mes: 10,
    dia: 3,
    categoria: 'Culto',
    gcal: '20261003/20261004',
  },
  {
    id: 'ev_15',
    titulo: 'Reunião Geral',
    data: '2026-10-06',
    dataFormatada: '06/10/2026',
    mes: 10,
    dia: 6,
    categoria: 'Reunião Geral',
    gcal: '20261006/20261007',
  },
  {
    id: 'ev_16',
    titulo: 'Reunião Geral',
    data: '2026-11-03',
    dataFormatada: '03/11/2026',
    mes: 11,
    dia: 3,
    categoria: 'Reunião Geral',
    gcal: '20261103/20261104',
  },
  {
    id: 'ev_17',
    titulo: 'Reunião Geral',
    data: '2026-12-01',
    dataFormatada: '01/12/2026',
    mes: 12,
    dia: 1,
    categoria: 'Reunião Geral',
    gcal: '20261201/20261202',
  },
  {
    id: 'ev_18',
    titulo: 'Confraternização do Louvor 2026',
    data: '2026-12-05',
    dataFormatada: '05/12/2026',
    mes: 12,
    dia: 5,
    categoria: 'Confraternização',
    gcal: '20261205/20261206',
  },
];

// Dados de Confraternização extraídos da Página 2 do PDF
export const OFICIAL_CONFRA: ParticipanteConfra[] = [
  { id: 'c_1', nome: 'Eduardo Medeiros', set: 'Pendente', out: 'Pendente', nov: 'Pendente' },
  { id: 'c_2', nome: 'Talita Costa', set: 'Pendente', out: 'Pendente', nov: 'Pendente' },
  { id: 'c_3', nome: 'Andressa Pyrro', set: 'Pendente', out: 'Pendente', nov: 'Pendente' },
  { id: 'c_4', nome: 'Aurenir', set: 'Pendente', out: 'Pendente', nov: 'Pendente' },
  { id: 'c_5', nome: 'Edigar Brito', set: 'Pendente', out: 'Pendente', nov: 'Pendente' },
  { id: 'c_6', nome: 'Eduarda Medeiros', set: 'Pendente', out: 'Pendente', nov: 'Pendente' },
  { id: 'c_7', nome: 'Eduardo Angelo', set: 'Pendente', out: 'Pendente', nov: 'Pendente' },
  { id: 'c_8', nome: 'Gabriel Pereira', set: 'Pendente', out: 'Pendente', nov: 'Pendente' },
  { id: 'c_9', nome: 'Gilson Nobrega', set: 'Pendente', out: 'Pendente', nov: 'Pendente' },
  { id: 'c_10', nome: 'Helenice Batista', set: 'Pendente', out: 'Pendente', nov: 'Pendente' },
  { id: 'c_11', nome: 'Hellen Silva', set: 'Pendente', out: 'Pendente', nov: 'Pendente' },
  { id: 'c_12', nome: 'Hercílio', set: 'Pendente', out: 'Pendente', nov: 'Pendente' },
  { id: 'c_13', nome: 'Ismael Junior', set: 'Pendente', out: 'Pendente', nov: 'Pendente' },
  { id: 'c_14', nome: 'Jamilly Nobrega', set: 'Pendente', out: 'Pendente', nov: 'Pendente' },
  { id: 'c_15', nome: 'Jerdely', set: 'Pendente', out: 'Pendente', nov: 'Pendente' },
  { id: 'c_16', nome: 'João Victor', set: 'Pendente', out: 'Pendente', nov: 'Pendente' },
  { id: 'c_17', nome: 'John Araújo', set: 'Pendente', out: 'Pendente', nov: 'Pendente' },
  { id: 'c_18', nome: 'Laís', set: 'Pendente', out: 'Pendente', nov: 'Pendente' },
  { id: 'c_19', nome: 'Lucas Gabriel', set: 'Pendente', out: 'Pendente', nov: 'Pendente' },
  { id: 'c_20', nome: 'Lucas Lopes', set: 'Pendente', out: 'Pendente', nov: 'Pendente' },
  { id: 'c_21', nome: 'Luiz Emmanuel', set: 'Pendente', out: 'Pendente', nov: 'Pendente' },
  { id: 'c_22', nome: 'Maria Eduarda', set: 'Pendente', out: 'Pendente', nov: 'Pendente' },
  { id: 'c_23', nome: 'Naara Oliveira', set: 'Pendente', out: 'Pendente', nov: 'Pendente' },
  { id: 'c_24', nome: 'Narjan Andrade', set: 'Pago', out: 'Pendente', nov: 'Pendente' },
  { id: 'c_25', nome: 'Rafael Pyrro', set: 'Pendente', out: 'Pendente', nov: 'Pendente' },
  { id: 'c_26', nome: 'Thiago de Souza', set: 'Pago', out: 'Pago', nov: 'Pago' },
  { id: 'c_27', nome: 'Vitor Nascimento', set: 'Pendente', out: 'Pendente', nov: 'Pendente' },
  { id: 'c_28', nome: 'Pastora Talita Brito', set: 'Pendente', out: 'Pendente', nov: 'Pendente' },
  { id: 'c_29', nome: 'Lucas Sales', set: 'Pendente', out: 'Pendente', nov: 'Pendente' },
];

// Matriz de Frequência Histórica extraída da Página 4 do PDF
// Mapeamento de datas: '04/08/2026', '01/09/2026', '07/07/2026'
export const OFICIAL_FREQUENCIAS_MATRIZ: Record<string, Record<string, 'Presente' | 'Falta'>> = {
  '04/08/2026': {
    'Andressa Pyrro': 'Presente',
    'Angélica': 'Falta',
    'Aurenir': 'Presente',
    'Edigar Brito': 'Falta',
    'Eduarda Medeiros': 'Presente',
    'Eduardo Angelo': 'Presente',
    'Eduardo Medeiros': 'Presente',
    'Gabriel Pereira': 'Presente',
    'Gilson Nobrega': 'Falta',
    'Helenice Batista': 'Presente',
    'Hellen Silva': 'Falta',
    'Hercílio': 'Presente',
    'Isaac Leoncio': 'Falta',
    'Ismael Junior': 'Presente',
    'Jamilly Nobrega': 'Falta',
    'Jerdely': 'Falta',
    'João Victor': 'Presente',
    'John Araújo': 'Presente',
    'Laís': 'Presente',
    'Lucas Gabriel': 'Presente',
    'Lucas Lopes': 'Presente',
    'Luiz Emmanuel': 'Presente',
    'Maria Eduarda': 'Presente',
    'Naara Oliveira': 'Presente',
    'Narjan Andrade': 'Presente',
    'Rafael Pyrro': 'Presente',
    'Talita Costa': 'Falta',
    'Thiago de Souza': 'Presente',
    'Vitor Nascimento': 'Presente',
  },
  '01/09/2026': {
    'Andressa Pyrro': 'Presente',
    'Angélica': 'Falta',
    'Aurenir': 'Falta',
    'Edigar Brito': 'Falta',
    'Eduarda Medeiros': 'Presente',
    'Eduardo Angelo': 'Falta',
    'Eduardo Medeiros': 'Falta',
    'Gabriel Pereira': 'Presente',
    'Gilson Nobrega': 'Presente',
    'Helenice Batista': 'Presente',
    'Hellen Silva': 'Falta',
    'Hercílio': 'Falta',
    'Isaac Leoncio': 'Falta',
    'Ismael Junior': 'Presente',
    'Jamilly Nobrega': 'Presente',
    'Jerdely': 'Presente',
    'João Victor': 'Presente',
    'John Araújo': 'Presente',
    'Laís': 'Presente',
    'Lucas Gabriel': 'Falta',
    'Lucas Lopes': 'Falta',
    'Luiz Emmanuel': 'Presente',
    'Maria Eduarda': 'Presente',
    'Naara Oliveira': 'Presente',
    'Narjan Andrade': 'Presente',
    'Rafael Pyrro': 'Presente',
    'Talita Costa': 'Falta',
    'Thiago de Souza': 'Presente',
    'Vitor Nascimento': 'Falta',
  },
  '07/07/2026': {
    'Andressa Pyrro': 'Presente',
    'Angélica': 'Falta',
    'Aurenir': 'Falta',
    'Eduarda Medeiros': 'Presente',
    'Eduardo Angelo': 'Falta',
    'Gabriel Pereira': 'Presente',
    'Gilson Nobrega': 'Presente',
    'Helenice Batista': 'Presente',
    'Hellen Silva': 'Falta',
    'Hercílio': 'Presente',
    'Isaac Leoncio': 'Presente',
    'Ismael Junior': 'Presente',
    'Jamilly Nobrega': 'Presente',
    'Jerdely': 'Presente',
    'João Victor': 'Presente',
    'John Araújo': 'Presente',
    'Laís': 'Presente',
    'Lucas Gabriel': 'Presente',
    'Lucas Lopes': 'Presente',
    'Luiz Emmanuel': 'Presente',
    'Maria Eduarda': 'Presente',
    'Naara Oliveira': 'Presente',
    'Narjan Andrade': 'Presente',
    'Rafael Pyrro': 'Presente',
    'Thiago de Souza': 'Falta',
    'Vitor Nascimento': 'Presente',
    'Erick Melo': 'Presente',
    'Yasmim Evely': 'Presente',
    'Edigar': 'Falta',
  },
};
